name: CHECK BRANCH
# on: [push]
jobs:
  CHECK:
    name: Verificando integridade da branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Node Install
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Lint/SASS
        run: npm run lint:sass

      - name: Build
        run: npm run build:core